### ISSUE TITLE
[1.16.5] Goggles don't apply to item tooltips

### ISSUE THREAD

**Issue by SDPhantom** [Robocraft999/CreatePlus#12]
Minecraft 1.16.5
Forge 36.2.8
Create 0.3.2d
Create Plus 0.3.2.1
Curios API 4.0.5.3

Goggles in a Curio slot and the goggle helmets don't reveal the stress and required RPM numbers in item tooltips. For an example of how this should work, place the original Goggles in the helmet slot and mouseover a machine or generator in JEI or inventory.

**Comment by Robocraft999** [comment]
Thats theoreticly already in the mod, but its not on curseforge, because I am currently working on the curio backtank, but if you want i can release a version without the curio backtank but with the tooltip

**Comment by Robocraft999** [comment]
its uploaded now
