### ISSUE TITLE
[Suggestion] Easier Curios support for Goggles?

### ISSUE THREAD

**Issue by Lgmrszd** [Robocraft999/CreatePlus#21]
Looks like in order to add Curios support for goggles, you recreated `GoggleOverlayRenderer` class, which may broke if something internally changes in Create.
Now, according to existing `GoggleOverlayRenderer` in Create itself, it is possible to enable Overlay by registering custom conditions with the method `registerCustomGoggleCondition`
I haven't tried that approach yet but I suppose it would be much easier to use this way.

**Comment by JieningYu** [comment]
ex. this
https://github.com/JieningYu/CreatePlus-mod/blob/mod/quilt/1.18.2/src/main/java/me/jieningyu/createplus/compat/Trinkets.java

using `GogglesItem.addIsWearingPredicate`.

**Comment by Robocraft999** [comment]
done
