### ISSUE TITLE
meka comb

### ISSUE THREAD

**Issue by ZEROX7** [Robocraft999/CreatePlus#29]
for some reason jei doesnt show any recipe for the create googles card, mabye broken recipe?

**Comment by Robocraft999** [comment]
Can you specify the version of create plus? Mekanism is installed right?

**Comment by ZEROX7** [comment]
sure
createplus-1.19.2_v0.5.2.jar
Mekanism-1.19.2-10.3.3.470.jar

**Comment by Robocraft999** [comment]
I am dumb. I accidently deleted the recipe in the port. I fix it today.
