### ISSUE TITLE
[1.16.5] Server crash

### ISSUE THREAD

**Issue by ocram9** [Robocraft999/CreatePlus#3]
Can't run this mod on a server since the latest update (1.16.4_0.3.2)

Crash report: https://gist.github.com/ocram9/e6c519ab25d60cd741408853e05a30d1

**Comment by Biologiker** [comment]
Maybe you used an old Forge Version?

**Comment by Biologiker** [comment]
Ok, i didnt found the problem. But as an solution you can use an older Version of the Mod.

**Comment by Biologiker** [comment]
> Maybe you used an old Forge Version?

Didnt worked for me

**Comment by Robocraft999** [comment]
I see what the problem is. I will fix it tomorow an reupload the mod. It has nothing to do with the forge version.
