### ISSUE TITLE
Goggles not working

### ISSUE THREAD

**Issue by romaust** [Robocraft999/CreatePlus#4]
Goglen in slot or with helment dont show RPM.
[Curios slot](https://psv4.userapi.com/c534536/u47511080/docs/d33/9c3c6c8f4c64/2021-06-22_23_02_43.png?extra=6aSD1Hb__xK7Q78yMGFLmKGM2j6b8jRgWmBpHIANN46A8K_CAWQ__U8Oj5uCOPuNqDg7VY32JmhPiYzQxt2Ww_oOAwVlq1NTIw5W7TqqmvoDk-zTZPv3o6y456wZdN9a00ovwMUDYpwMRQalLWq9)
[Goggle helmet](https://psv4.userapi.com/c534536/u47511080/docs/d39/c1e304119553/2021-06-22_23_02_35.png?extra=_AJN07RaZe98hKrrCMQl5DzJyqYgjayn2aTEyHPJajnixztiHjeM_5ltz4noxaS6Z28G8LLYjQs219dZbTtSrdcCmjtL-t4_nyK2HrypRxIcPFn4SiHgQR6deV4Jtn_h-gvuzrudODJRXIo8YfpK)
[Only goggle](https://psv4.userapi.com/c520036/u47511080/docs/d20/77538204f2aa/2021-06-22_23_02_48.png?extra=iiqjf7oBBTthdF0ov-t0qfE5LRay4zjd2iZSHFu6hGe4wBm4g2BkU8yPat660zE_0Fpq5CKFeckrf-RVYsAGtgyRvCoOApbjopwfJQ8kc1z1pHGK36tQAjugSBWHVGrOIDaDmSRu_OIf9fMRUicc)

**Comment by Robocraft999** [comment]
Do you mean of the items or in-world ?

**Comment by Robocraft999** [comment]
Okay I am working on it

**Comment by Robocraft999** [comment]
no added
