### ISSUE TITLE
Crashes with 3.2 create

### ISSUE THREAD

**Issue by Muvkina** [Robocraft999/CreatePlus#5]
Crashes with create v3.2 seems to be in the goggleoverlay renderer. Here is a pastebin of the log https://paste.ee/p/feJ1D

**Comment by ModernGamingWorld** [comment]
Same Just got the same crash

**Comment by laceflower** [comment]
Can also confirm this crash - seems like 3.2 breaks most addons.

**Comment by dajiuji** [comment]
Me too

**Comment by Dunkmania101** [comment]
I'll add myself to the list of people confirming this (I also had this crash).

**Comment by ModernGamingWorld** [comment]
@Robocraft999 Any update on a fix, I saw you were just active on Curseforge 15hours ago

**Comment by Robocraft999** [comment]
Yes I fixed it. it will be uploaded today
